"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import classifysingleresponse as shared_classifysingleresponse
from typing import Optional



@dataclasses.dataclass
class ClassifyDocumentSyncResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    bad_request: Optional[str] = dataclasses.field(default=None)
    r"""Bad Request"""
    classify_single_response: Optional[shared_classifysingleresponse.ClassifySingleResponse] = dataclasses.field(default=None)
    r"""The document type and reference documents in the Sensible account that are most similar to this document."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    sensible_encountered_an_unknown_error: Optional[str] = dataclasses.field(default=None)
    r"""Internal Server Error"""
    unauthorized: Optional[str] = dataclasses.field(default=None)
    r"""Not authorized"""
    unsupported_media_type: Optional[str] = dataclasses.field(default=None)
    r"""Unsupported Media Type"""
    

